Coursework-5 Функционал проверки правильных ответов
mondayseptember/LearnEnglishWordsTelegramBot pull request #5
Opened 2024-02-06 21:05 UTC by mondayseptember

2024-02-12 11:48 UTC, danelyan requested changes

2024-02-12 11:48 UTC, danelyan commented on src/main/kotlin/Main.kt
> +fun File.saveDictionary(dictionary: MutableList<Word>) {
лучше не перебарщивать с extension-функциями. Если выше мы можем сказать что для изменяемого списка слов (MutableList<Word>) применима фильтрация выученных слов (filterLearnedWords())

То для любого файла не применимо "сохранение словаря". Тем самым ты "засоряешь" скоуп файла. Например, другой программист который в том же проекте что и ты для файла настроек сделает автокомплит увидит saveDictionary, и еще кучу ненужных других экстеншенов.

Давай сделаем обычной функцией

2024-02-12 11:48 UTC, danelyan commented on src/main/kotlin/Main.kt
> +                    for (i in learningWord) {
зачем этот цикл? learningWord всегда из одного элемента

2024-02-12 11:48 UTC, danelyan commented on src/main/kotlin/Main.kt
> +                    val learningWord = shuffledWords.take(1)
Если тебе нужно рандомное слово, напиши просто shuffledWords.random(), тогда ни take ни цикл тебе будут не нужны

2024-02-13 15:17 UTC, mondayseptember commented
Подскажи, пожалуйста, если при запуске программы только у одного слова correctAnswersCount меньше 3, в режиме изучения должно появляться только это слово или другие тоже?

2024-02-13 15:53 UTC, danelyan requested changes

2024-02-13 15:53 UTC, danelyan commented on src/main/kotlin/Main.kt
> +                    val learningWord = shuffledWords.random()
Выше ты сначала дополняешь shuffledWords выученными словами, а потом делаешь random().
Тогда learningWord может оказаться уже выученным. Лучше слово отбирать до примешивания

2024-02-13 15:53 UTC, danelyan commented on src/main/kotlin/Main.kt
> +            wordsFile.appendText(it.original + "|" + it.translate + "|" + it.correctAnswersCount + "\n")
давай тут шаблоном строки сделаем ( `"${it.original}|${ ...` )

2024-02-14 00:32 UTC, danelyan approved these changes

2024-02-14 18:48 UTC, merged