Coursework-9 Интерфейс, доработка телеграм бота
mondayseptember/LearnEnglishWordsTelegramBot pull request #9
Opened 2024-03-04 10:49 UTC by mondayseptember

2024-03-04 10:56 UTC, mondayseptember commented
1. Не совсем поняла как создать extension-функцию substringAfter с параметром CALLBACK_DATA_ANSWER_PREFIX
2. При попытке привести ChatId к .toInt() падает ошибка, со String работает
![image](https://github.com/mondayseptember/LearnEnglishWordsTelegramBot/assets/91486272/090f8701-717c-4a25-9055-a5d27d838be2)

2024-03-05 18:11 UTC, danelyan requested changes

2024-03-05 18:11 UTC, danelyan commented on src/main/kotlin/Telegram.kt
> +        if (userMessage == "/start" && chatId != null) {
обрати внимание, что если chatId == null, код ничего не делает.
можно делать continue сразу:
```Kotlin
val chatId = chatIdRegex.find(updates)?.groups?.get(1)?.value ?: continue
```

2024-03-05 18:11 UTC, danelyan commented on src/main/kotlin/Telegram.kt
> +        TelegramBotService(botToken).sendMessage(
TelegramBotService не стоит создавать каждый раз как он потребуется, ведь выше есть переменная telegramBot, передавай ее сюда

2024-03-05 18:11 UTC, danelyan commented on src/main/kotlin/Telegram.kt
> +        val chatId = chatIdRegex.find(updates)?.groups?.get(1)?.value
Конвертация в Int не работает, потому что выходит за границы возможных значений.
https://kotlinlang.org/docs/numbers.html
Советую выучить хотя бы примерный порядок диапазонов для типов данных, могут спросить на собеседовании

2024-03-05 18:11 UTC, danelyan commented on src/main/kotlin/TelegramBotService.kt
> +                                "text": "Меню",
Попробуй сначала декомпозировать:

```Kotlin
val variantsString = """
{
      "text": "${question.variants[0].translate}", 
      "callback_data": "$CALLBACK_DATA_ANSWER_PREFIX${variants[0]}"
  },
  {
      "text": "${question.variants[1].translate}", 
      "callback_data": "$CALLBACK_DATA_ANSWER_PREFIX${variants[1]}" 
  }, 
  {
      "text": "${question.variants[2].translate}", 
      "callback_data": "$CALLBACK_DATA_ANSWER_PREFIX${variants[2]}" 
  },
  {
      "text": "${question.variants[3].translate}", 
      "callback_data": "$CALLBACK_DATA_ANSWER_PREFIX${variants[3]}" 
  }
"""

val sendQuestionBody = """ 
            {
                "chat_id": $chatId,
                "text": "${question.correctAnswer.original}",
                "reply_markup": {
                    "inline_keyboard": [
                        [
                            $variantsString,
                            {
                                "text": "Меню", 
                                "callback_data": "$MENU" 
                            }
                        ]
                    ]
                }
            }
        """.trimIndent()
```

Обрати внимание, что 
```json
{
    "text": "${question.variants[3].translate}", 
    "callback_data": "$CALLBACK_DATA_ANSWER_PREFIX${variants[3]}" 
}
```
повторяется на каждый variant из question.variants и соединяется запятой. То есть нам надо каждый variant смапить в строку, а вместо цифры использовать индекс:

```Kotlin
        val variantsString = question.variants
            .mapIndexed { index, word ->
                """
                    {
                        "text": "${word.translate}", 
                        "callback_data": "$CALLBACK_DATA_ANSWER_PREFIX${index}" 
                    }
                 """.trimIndent()
            }
            .joinToString(separator = ",")
```

2024-03-05 18:11 UTC, danelyan commented on src/main/kotlin/TelegramBotService.kt
> +        val client: HttpClient = HttpClient.newBuilder().build()
client можно вынести в поле класса, чтобы не создавать каждый запрос

2024-03-06 11:28 UTC, danelyan approved these changes
Отлично! Переходим к финалу )

2024-03-07 06:44 UTC, merged